"""Host-side callback broker: a JSON-RPC endpoint the workload container may call.

Why this exists
---------------
The shim's premise is that rich tooling belongs in a container, away from the host.
That isolation is one-directional, though: a few capabilities *only* the host has —
a credential in an OS keyring, a native filesystem, git itself — cannot be moved
into the container without dragging their liability along. Today those are pushed
inward (a token handed across the seam by `cli.GITHUB_TOKEN_ENV`). The broker is
the inversion: instead of shipping the *capability* into the container, the host
keeps it and exposes a **narrow verb** the container may ask it to perform.

That is strictly better on two axes. The container ends up holding no token and
needing no network; and host-only work (native git on a native filesystem) stops
crossing the bind-mount seam, where a 9p/drvfs translation makes some of it simply
impossible.

This module is **Step 1**: transport, auth, and dispatch — and nothing else. The
only verbs are ``ping`` and ``broker.info``. Everything else is **refused**. The
point of landing it verb-less is that the refusal path is the security-relevant
one, so it is worth getting right and testing before there is anything valuable
behind it.

Design constraints
------------------
Stdlib only, like the rest of this repo — a host-installed daemon is the last
place to want a dependency tree.

Written self-contained (it imports nothing from the shim) so it can later be
lifted into a shared ``host-broker`` package. It is deliberately NOT extracted
yet: there is exactly one consumer, and a shared package with one consumer is a
guess about the second one.

Security posture
----------------
Bound to an ephemeral port on ``127.0.0.1`` by default, with a per-run token
generated by ``secrets.token_urlsafe``. The token is the real gate: it is compared
with ``hmac.compare_digest``, and a request that fails it is answered 401 with
nothing else parsed or dispatched. Bind breadth is defense in depth on top of that,
not instead of it — if a Docker Desktop container turns out to be unable to reach a
loopback listener, widening the bind is an acceptable trade because the token still
stands between the port and any verb.

The token is never logged. The audit line records the method and the outcome,
which is what an operator needs, and nothing that would let a reader of the log
replay the call.
"""

from __future__ import annotations

import hmac
import json
import logging
import secrets
import threading
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Callable

# Bumped when the wire contract changes; reported by `broker.info` so a client can
# tell what it is talking to before it depends on a verb existing.
BROKER_VERSION = "1"

# JSON-RPC 2.0 error codes (the standard-reserved range). -32601 is the important
# one here: it is how the broker says "no" to everything not on the list.
PARSE_ERROR = -32700
INVALID_REQUEST = -32600
METHOD_NOT_FOUND = -32601
INVALID_PARAMS = -32602

_LOG = logging.getLogger("mono_control_shim.broker")

# Audit goes to stderr, so it never contaminates the container's stdout — which is
# the artifact's actual output and may be piped.
#
# The default level is WARNING, not INFO, and the choice is deliberate: at WARNING the
# lines that appear are exactly the ones an operator needs to see unprompted — an
# authentication failure or a refused method, i.e. someone asking the host for
# something it does not do. A per-request success line at INFO would interleave with
# the artifact's own output on every interactive run and quickly train the reader to
# ignore the stream, which is the opposite of an audit trail. The full per-request log
# is one line away when you want it::
#
#     logging.getLogger("mono_control_shim.broker").setLevel(logging.INFO)
_AUDIT_LEVEL = logging.WARNING


def _configure_logging() -> None:
    """Attach a stderr handler once, unless the embedding app already set one up."""
    if _LOG.handlers or _LOG.level != logging.NOTSET:
        return  # a caller has opinions; don't override them
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter("mono-broker: %(message)s"))
    _LOG.addHandler(handler)
    _LOG.setLevel(_AUDIT_LEVEL)

# name -> handler. A dict, not a plugin system: the whole value of this registry is
# that reading it tells you the complete set of things the host will do.
_VERBS: dict[str, Callable[[dict[str, Any]], Any]] = {}


def verb(name: str) -> Callable[[Callable[[dict[str, Any]], Any]], Callable[[dict[str, Any]], Any]]:
    """Register a handler under *name*. Unregistered methods are refused."""

    def register(func: Callable[[dict[str, Any]], Any]) -> Callable[[dict[str, Any]], Any]:
        _VERBS[name] = func
        return func

    return register


@verb("ping")
def _ping(params: dict[str, Any]) -> str:
    """Liveness. Deliberately trivial and side-effect-free.

    This is the verb the container-reachability spike asserts on, so it must prove
    the whole path — routing, auth, dispatch, envelope — while proving nothing about
    the host's state.
    """
    return "pong"


@verb("broker.info")
def _info(params: dict[str, Any]) -> dict[str, Any]:
    """Self-description: wire version plus the exact set of callable verbs.

    Advertising the verb list is not a leak — the refusal is enforced server-side
    regardless — and it makes the boundary inspectable from inside the container,
    which is where someone debugging a refusal actually is.
    """
    return {"version": BROKER_VERSION, "methods": sorted(_VERBS)}


class _Handler(BaseHTTPRequestHandler):
    """One request: authenticate, parse, dispatch, answer.

    The order matters and is not an implementation detail: authentication happens
    **before** the body is read or parsed, so an unauthenticated caller cannot reach
    the JSON parser at all.
    """

    # POST-only, JSON-RPC over a single path. There is no GET surface on purpose:
    # nothing here is a resource, and a browser wandering into it should find nothing.
    protocol_version = "HTTP/1.1"
    server_version = f"mono-control-shim-broker/{BROKER_VERSION}"
    sys_version = ""  # don't advertise the host's Python build

    # Set by BrokerServer when the socket is created.
    token: str = ""

    def log_message(self, format: str, *args: Any) -> None:
        """Route the stdlib's per-request line into logging instead of raw stderr."""
        _LOG.debug("%s - %s", self.address_string(), format % args)

    def _authenticated(self) -> bool:
        """True when the request carries the exact bearer token for this run.

        ``compare_digest`` rather than ``==``: the comparison is against a secret and
        the caller controls the input, which is the textbook timing-oracle shape. It
        costs nothing to not have that conversation.
        """
        header = self.headers.get("Authorization", "")
        scheme, _, presented = header.partition(" ")
        if scheme.lower() != "bearer" or not presented:
            return False
        return hmac.compare_digest(presented, self.token)

    def _respond(self, status: HTTPStatus, payload: dict[str, Any]) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _error(self, code: int, message: str, *, request_id: Any = None) -> None:
        """A JSON-RPC error envelope. HTTP stays 200; the error lives in the body.

        That is the JSON-RPC convention — the transport succeeded, the call did not —
        and it keeps 401 meaning exactly one thing: you did not authenticate.
        """
        self._respond(
            HTTPStatus.OK,
            {"jsonrpc": "2.0", "id": request_id, "error": {"code": code, "message": message}},
        )

    def do_POST(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler's naming
        if not self._authenticated():
            # No method to name yet: refusing before parse is the point.
            _LOG.warning("auth=fail outcome=401")
            self._respond(HTTPStatus.UNAUTHORIZED, {"error": "unauthorized"})
            return

        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            length = 0
        raw = self.rfile.read(length) if length > 0 else b""

        try:
            request = json.loads(raw)
        except (ValueError, UnicodeDecodeError):
            _LOG.warning("auth=ok outcome=parse-error")
            self._error(PARSE_ERROR, "parse error")
            return

        if not isinstance(request, dict) or request.get("jsonrpc") != "2.0":
            _LOG.warning("auth=ok outcome=invalid-request")
            self._error(INVALID_REQUEST, "invalid request")
            return

        request_id = request.get("id")
        method = request.get("method")
        params = request.get("params", {})
        if not isinstance(method, str):
            _LOG.warning("auth=ok outcome=invalid-request")
            self._error(INVALID_REQUEST, "invalid request", request_id=request_id)
            return
        if not isinstance(params, dict):
            # Only by-name params are accepted. Positional params would make every
            # future verb's signature part of the wire contract; named ones let a
            # verb grow an optional argument without breaking an older caller.
            _LOG.warning("method=%s auth=ok outcome=invalid-params", method)
            self._error(INVALID_PARAMS, "params must be an object", request_id=request_id)
            return

        handler = _VERBS.get(method)
        if handler is None:
            # THE refusal. Anything not explicitly registered is not something the
            # host will do, and saying so is the broker's most important behavior.
            _LOG.warning("method=%s auth=ok outcome=refused", method)
            self._error(METHOD_NOT_FOUND, f"method not found: {method}", request_id=request_id)
            return

        try:
            result = handler(params)
        except Exception:
            # A verb blowing up must not take the daemon down with it, and must not
            # spill host internals across the seam: the traceback goes to the host's
            # log, the container gets a flat "internal error".
            _LOG.exception("method=%s auth=ok outcome=error", method)
            self._error(INVALID_PARAMS, "internal error", request_id=request_id)
            return

        _LOG.info("method=%s auth=ok outcome=ok", method)
        self._respond(HTTPStatus.OK, {"jsonrpc": "2.0", "id": request_id, "result": result})


class BrokerServer:
    """A running broker: ephemeral port, per-run token, background thread.

    Used as a context manager around a container run::

        with BrokerServer() as broker:
            ...  # broker.port / broker.token get injected into the container

    The port is ephemeral (bind to 0, read back what the OS gave us) and the token
    is fresh per instance, so two concurrent `mproj` invocations cannot collide or
    speak to each other's broker.
    """

    def __init__(self, bind_addr: str = "127.0.0.1") -> None:
        self.bind_addr = bind_addr
        self.token = secrets.token_urlsafe(32)
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None

    @property
    def port(self) -> int:
        """The bound port. Raises if asked before the server is started."""
        if self._server is None:
            raise RuntimeError("broker is not running")
        return self._server.server_address[1]

    def start(self) -> None:
        """Bind and serve. Propagates ``OSError`` so the caller can decide.

        It does not decide for itself, because in Step 1 the broker is best-effort:
        `cli` warns and runs the container anyway. Swallowing the error here would
        take that choice away from the one place that knows whether it matters.
        """
        _configure_logging()
        handler = type("_BoundHandler", (_Handler,), {"token": self.token})
        self._server = ThreadingHTTPServer((self.bind_addr, 0), handler)
        # daemon=True so a wedged request can never keep the shim alive after the
        # container run it exists to serve has finished.
        self._thread = threading.Thread(
            target=self._server.serve_forever, name="mono-broker", daemon=True
        )
        self._thread.start()
        _LOG.info("broker listening on %s:%d", self.bind_addr, self.port)

    def stop(self) -> None:
        """Shut down and release the port. Safe to call twice."""
        if self._server is not None:
            self._server.shutdown()
            self._server.server_close()
            self._server = None
        if self._thread is not None:
            self._thread.join(timeout=5)
            self._thread = None

    def __enter__(self) -> "BrokerServer":
        self.start()
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.stop()
